### PR TITLE
ListCard, Dismiss, Animations, Sorting, StaggeredGridView, BugFixes

### PR DESCRIPTION
**Pull request by FHellmann**
Simplify the MaterialListViewAdapter and MaterialListView. Added the
Function to directly dismiss a Card without swiping it away.

### CODE REVIEW

**Comment by FHellmann** [comment]
@theblixguy I refactored the code to get MaterialListView and MaterialStaggeredGridView run and interact the same. It's now done. In the sample code I use both, the MaterialListView for normal  and the MaterialStaggeredGridView for larger screen sizes.

**Smartphone**
smartphone

**Tablet 7"**
tablet_7

**Tablet 10"**
tablet_10

**Comment by dexafree** [comment]
Wow, the work you have made is awesome!

I've been making some tests these days, and all is working like a charm.

I've just tested the last commit you made, and i also works very well, so first of all, thank you for your great work!

I will merge this right now, and write the new documentation.

I expect to upload the new version to Maven today ;)

**Comment by dexafree** [comment]
* Updated README.md
* Created Wiki pages
* Uploaded version 2.0.0 to maven centrla (available in some hours)
* Sample APK uploaded to Google Play (available in some hours)

**Comment by FHellmann** [comment]
Thank you very much!

I'm not very happy to seperate the MaterialListView and MaterialStaggeredGridView. I would like to put them together, but the StaggeredGridView does not support only one column! (I've seen you write this in the documentation, maybe you could change it ;) )

Maybe I or you will find a better solution. But for the first time, it's working! :)

**Comment by dexafree** [comment]
Thank you for your work!

The Readme.md has been updated

I'll take a deeper look to the separation, hope there's a way to implement both of them in the same class

**Pull request merged**
