### PR TITLE
Added url load with Picasso

### PR DESCRIPTION
**Pull request by RicardoRB**
I added new behaviour where you can load a image from a url website sending a string to setDrawable.

### CODE REVIEW

**Comment by dexafree** [comment]
I've been making a few tests and the image hardly ever loads (I don't know why, and sometimes the same image loads after several tries).

Does it also happen to you?

**Comment by RicardoRB** [comment]
No, it work fine in my app, I did not so much as pass a string to Picasso. It must work nice... :persevere:

**Comment by dexafree** [comment]
Yes, I know, that's why I don't understand how it's not working.

Could you please post a few image URL's that work fine to you?

Thanks!

**Comment by RicardoRB** [comment]
Here you go!
```java
card.setDrawable("http://i.telegraph.co.uk/multimedia/archive/03025/saatchi-plug-hole_3025834k.jpg");
card.setDrawable("http://i.telegraph.co.uk/multimedia/archive/03025/saatchi-train_3025820k.jpg");
card.setDrawable("http://i.telegraph.co.uk/multimedia/archive/03025/saatchi-liberty_3025823k.jpg");
card.setDrawable("http://i.telegraph.co.uk/multimedia/archive/03025/saatchi-fall_3025829k.jpg");
```

**Comment by dexafree** [comment]
Nevermind, my fault.
It was a stupid error, the sample APK did not have the INTERNET permission declared.

Will test a few more things this evening and merge this weekend

**Comment by RicardoRB** [comment]
Great! :smile:

**Comment by dexafree** [comment]
I'm trying to define an understandable API in order to set Placeholders.
Tomorrow I will finish it, merge and finally upload to MVN Central

**Comment by RicardoRB** [comment]
Sweet! I was thinking if importing Picasso from MateriaList gradle could be a problem because MaterialList have ```compile 'com.squareup:otto:1.3.5'``` and if it is, maybe the user should import it from gradle app

**Comment by dexafree** [comment]
Why should it be a problem?
Do you mean, by adding two Square libraries at the same time?

**Comment by RicardoRB** [comment]
Yes, that's what I am talking about

**Comment by dexafree** [comment]
It's only the publisher id, gradle should not complain about that

**Comment by dexafree** [comment]
From now I will merge and edit the sample app.
I'm thinking on adding an `AsyncImageCard` class, but I'm not sure about it.

Thanks ;)

**Pull request merged**
