### PR TITLE
Code Refactoring, Simplifications, Patterns, Annotations, Fixed Issues

### PR DESCRIPTION
**Pull request by FHellmann**
This PR should make the coding much easier for every developer and reduces the Library size.

*What I've done at all:*
* **Builder Pattern**: to easily create new Cards
* **Observer Pattern**: to replace the Eventbus Otto with
* **Library shrinking**: by replacing Libraries with an easy java implementation
* **Java Doc**: added to understand the code much easier and faster

*Fixed issues:*
#92 With the Renderer principle it should be easy to create a Card programmaticly.
#77 Should be fixed with Observer Pattern
Maybe some others are also fixed with this PR...

### CODE REVIEW

**Comment by dexafree** [comment]
Wow, thanks!

I was thinking about the Builder pattern too.

I will make some tests today and tomorrow, but I'm sure it will all be great :+1: 

Thanks again :)

**Comment by dexafree** [comment]
I've been taking a look at the code, and I'm not sure about the new Builder API.

Let me explain.

You splitted the Card information in Two:

1. The Card.Builder, which only takes responsibility for the dismissable boolean, the Tag, and the build method, which takes a CardRenderer object.
2. The CardRenderer, which has the actual information of the card (title, subtitle, image...).

In my opinion, the Card should be responsible of the Card information, and the Renderer only should be in charge of things like the ImageLoadedListener, apart from being optional.

The inheritance by composition by making a Builder which has no real responsibility... I'm not sure about it.

I was thinking in an API more like

```java
BigImageCard card = new BigImageCard.Builder(this)
    .setTitle("My title")
    .setDrawable("http://blablabla...")
    .withRenderer(renderer)
    .build();
```

The main target should be simplifying the developer API, and by nesting two builders I think it's like adding complexity to it.

The Card object returned would still have the setTitle, setSubtitle... methods, which would call the Observable methods (again, thanks a lot for that).

But again, I don't think the Renderer should be responsible of storing the Card real data.

**Comment by FHellmann** [comment]
I also thought about the same things. My main reason, why I decided to use 2 Builder Patterns ist, that the Card and it's CardLayout will never be changed again. Also if a new card type should be developed in the future. It can easily be created a new Render class and that's it. There for it is not neccessary to create 2 classes. One for the data holding and one for the layout which also has to be named in the XML. With the Render class this is all together. The XML file only need to name the CardLayout class for every kind of layout and the Render will take rest of it. Maybe the naming "Render" is not correct for this class but I don't know how to name it.

**Comment by FHellmann** [comment]
I've remebered me on a [project](https://github.com/amulyakhare/TextDrawable/blob/master/library/src/main/java/com/amulyakhare/textdrawable/TextDrawable.java) (called TextDrawable) where the same issue with 2 Builder Patterns exists. It was solved very handsome. I think this is what we both want to see, right? ;)

I tried to code a simple example which I will work out later more specificly:
```java
public class Card {
	
    //...

	public static class Builder<T extends ICardTypeConfig> implements ICardBuilder, ICardConfig<T>, ICardTypeConfig {
		public ICardConfig setTag(Object object) {}
		
		public ICardConfig dismissable() {...}
		
		public T startConfig() {...}
		
		public ICardConfig endConfig() {...}
		
		public Card build() {...}
	}
}

public interface ICardBuilder {
	Card build();
}

public interface ICardConfig<T extends ICardTypeConfig> {
	ICardConfig setTag(Object object);
	
	ICardConfig dismissable();
	
	T startConfig();
}

public interface ICardTypeConfig {
	ICardConfig endConfig();
}

// A sample config of a card type
public class BasicTextCardConfig implements ICardTypeConfig {
	public BasicTextCardConfig setTitle(String text) {...}
	
	public BasicTextCardConfig setDescription(String text) {...}

	public ICardConfig endConfig() {...}
}
```

What's your opinion about this solution?

**Comment by dexafree** [comment]
I was writing an answer about the extensibility of the library, that could be made by also extending the Builder, but then you wrote that and I saw that we were both looking for the same thing:

```java
public static class Builder<T extends ICardTypeConfig> implements ICardBuilder, ICardConfig<T>, ICardTypeConfig
```

That allows a pretty nice extensibility!

Although, which use would you give to the endConfig() method?

Also, I think the

```java
ICardConfig<T>
```

Should be 

```java
ICardConfig<T extends Card>
```

Right?

**Comment by FHellmann** [comment]
Mh... this is getting generics brain fuck :/

Ok, let's try this:
```java
public class Card {

    //...

    public static class Builder<T extends ICardTypeConfig> implements ICardBuilder, ICardConfig<T>, ICardTypeConfig<T> {
        public ICardConfig<T> setTag(Object object) {}

        public ICardConfig<T> dismissable() {...}

        public T startConfig() {...}

        public ICardConfig<T> endConfig() {...}

        public Card build() {...}
    }
}

public interface ICardBuilder {
    Card build();
}

public interface ICardConfig<T extends ICardTypeConfig> {
    ICardConfig<T> setTag(Object object);

    ICardConfig<T> dismissable();

    T startConfig();
}

public interface ICardTypeConfig<T extends ICardTypeConfig> {
    ICardConfig<T> endConfig();
}

// A sample config of a card type
public class BasicTextCardConfig implements ICardTypeConfig<BasicTextCardConfig> {
    public BasicTextCardConfig setTitle(String text) {...}

    public BasicTextCardConfig setDescription(String text) {...}

    public ICardConfig<BasicTextCardConfig> endConfig() {...}
}
```

Do you have a more handsome solution? :/

**Comment by dexafree** [comment]
What about getting rid of the ICardBuilder?
I don't think it's necessary, as the build() method is the Builder's main job. :worried: 

```java
public class Card {

    //...

    public static class Builder<T extends ICardTypeConfig> implements ICardConfig<T>, ICardTypeConfig<T> {
        public ICardConfig<T> setTag(Object object) {}

        public ICardConfig<T> dismissable() {...}

        public T startConfig() {...}

        public ICardConfig<T> endConfig() {...}

        public Card build() {...}
    }
}

public interface ICardConfig<T extends ICardTypeConfig> {
    ICardConfig<T> setTag(Object object);

    ICardConfig<T> dismissable();

    T startConfig();
}

public interface ICardTypeConfig<T extends ICardTypeConfig> {
    ICardConfig<T> endConfig();
}

// I LIKE THIS A LOT
// A sample config of a card type
public class BasicTextCardConfig implements ICardTypeConfig<BasicTextCardConfig> {
    public BasicTextCardConfig setTitle(String text) {...}

    public BasicTextCardConfig setDescription(String text) {...}

    public ICardConfig<BasicTextCardConfig> endConfig() {...}
}
```

I don't understand which which "separation" you want to achieve in this two interfaces:

```java
public interface ICardConfig<T extends ICardTypeConfig> {
    ICardConfig<T> setTag(Object object);

    ICardConfig<T> dismissable();

    T startConfig();
}

public interface ICardTypeConfig<T extends ICardTypeConfig> {
    ICardConfig<T> endConfig();
}
```

I understand the ICardConfig has the "information" methods, but the ICardTypeConfig has only the endConfig?

Which code would you write at the endConfig method?

(And yes, this is getting generic hell)

**Comment by FHellmann** [comment]
I think the ICardConfig and ICardTypeConfig should be seperated because the ICardConfig can all be implemented by the Builder itself. The ICardTypeConfig should be extendable and there for it has to be implemented by the concret Config class (e.g. BasicTextCardConfig). But you're right, the ICardBuilder interface is useless.
We can move the endConfig Method out of ICardTypeConfig to ICardConfig, that the Builder also implement this Method itself - this Method will never be changed i think?

```java
public interface ICardConfig<T extends ICardTypeConfig> {
    ICardConfig<T> setTag(Object object);

    ICardConfig<T> dismissable();

    T startConfig();

    ICardConfig<T> endConfig();
}

public interface ICardTypeConfig {
}
```

Maybe we should try something like this...
```java
public class Card<T extends ICardConfig> {

    //...

    public T getConfig() {...}

    public static class Builder<T extends ICardConfig> implements ICardBuilder<T> {
        public ICardConfig setTag(Object object) {}

        public ICardConfig dismissable() {...}

        public T startConfig() {...}

        public ICardConfig endConfig() {...}

        public Card<T> build() {...}
    }
}

public interface ICardBuilder<T extends ICardConfig> {
    ICardBuilder setTag(Object object);

    ICardBuilder dismissable();

    T startConfig();

    ICardBuilder endConfig();

    Card<T> build();
}

public interface ICardConfig {
}

public interface ICardRenderer extends ICardConfig {
    void render(View view, Card card);
}

public class BasicTextCardConfig implements ICardRenderer {
    public BasicTextCardConfig setTitle(String text) {...}

    public BasicTextCardConfig setDescription(String text) {...}

    public void render(View view, Card card) {...}
}
```
And this should result in...
```java
Card<BasicTextCardConfig> card = new Card.Builder<BasicTextCardConfig>(context)
                  .setTag("TEST")
                  .dismissable()
                  .startConfig()
                  .setTitle("Title")
                  .setDescription("End")
                  //... and a lot more ...
                  .endConfig()
                  .build();

// ... do something awesome ...

card.getConfig().setTitle("Other");
```

**Comment by dexafree** [comment]
Yes, I think this is a much nicer approach (thanks again for your help).

Also, I was thinking about the extensibility and if it could be possible to extend the Builder in the Card subclasses, so the final client code could invoke the Builder directly from the subclass name, something like

```java
BasicTextCard card = new BasicTextCard.Builder(context)
    .setTag("TEST")
    .dismissable()
    .setTitle("Title")
    .setDescription("Description")
    .build();
```

And that would be done by extending the Builder class, something like

```java
public class MyCard {

    // ....
    public static class Builder<MyCardConfig> implements ICardBuilder<MyCard>  {
        // new methods
    }

}
```

By the way, I just realized that the startConfig() and the endConfig() methods are a very nicely done wrapper, by the way.

PS: I really hope it improves the developer experience!

**Comment by FHellmann** [comment]
Do you want to realize your vision? Or do we both realize our own implmentations and then you choose the best?

By the way... Do you think it is more developer friendly if the Card class will always have a Generic type or to cast the Config from getConfig?

**Comment by dexafree** [comment]
By thinking about the Developer Experience, I think your approach is best.

About your question... I don't know, I think both have their pros and cons, I leave it up to you!

**Comment by FHellmann** [comment]
I think I've found the best solution. What do you think?

**Comment by dexafree** [comment]
Looks nice, although I'm not a huge fan of `newInstance()`, it's definitely worth a try.

I'll test it as soon as I can!

Thanks again :+1:

**Comment by FHellmann** [comment]
The alternative is, that the developer don't have to set withProvider(Provider.class) but withProvider(new Provider()). Both is fine. With the second option there is no need for ``` newInstance() ```.
I was not sure if I should split the Renderer and Content in two seperate things. Like...
```java
new Card.Builder(this)
            .withRenderer(new Renderer)
            .withContent(new ContentProvider)
            .setTitle(...)
            ...
```
Which way would you prefer?

**Comment by dexafree** [comment]
I like the current one, specially because of the cast you make to the `newInstance` result, which avoids the developer having to cast the returned `CardProvider`.

Also, a thing I had to change at the `CardProvider` : 

https://github.com/FHellmann/MaterialList/blob/master/materialList/src/main/java/com/dexafree/materialList/card/provider/CardProvider.java#L68

I had to change it to: 

```java
((CardView)view.findViewById(R.id.cardView)).setCardBackgroundColor(getBackgroundColor());
```

in order to avoid a ClassCastException.

Another thing: At your `BasicListCard` the checked items don't get persisted when scrolling.

Finally, I really like this new API, it makes it a pleasure to use, maybe even more than the Builder extension I was thinking (the `new BigImageCard.Builder(context)`).

Any other opinion about the new API vs the Builder extensions?

**Comment by FHellmann** [comment]
It's nice to know that there can be thrown a ClassCastException.

The checked items have to persist by the developer (e.g. in an object).

Thank you! :)

The only thing is what I already said. Maybe it's better to split the Content and Renderer classes. But I think this is a matter of taste.

**Comment by dexafree** [comment]
So, you think it's all ready for starting editing the wiki before making the migration?

**Comment by FHellmann** [comment]
Yes, I think so ;)

**Comment by dexafree** [comment]
Great, I'll start today :+1: 

I also plan to write a Wiki page about how to make the transition.

Thanks for your help and your PR!

**Comment by dexafree** [comment]
I've updated the Custom Card creation guide. Could you check it out and see if I missed something important?

https://github.com/dexafree/MaterialList/wiki/Create-your-own-Cards

**Comment by FHellmann** [comment]
It looks great. I think you said everything which can be said about this topic. It's also easy to understand and should be simple to follow these instructions.

**Pull request merged**
